using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

// Hard Stage-B cell: kinematically actuated visible hands; one free PhysX object.
// No parenting, joints, object transform writes after initialization, forces,
// springs, trajectories, catch surfaces, or post-physics repair are present.
public static class HybridBimanualCellBuilder
{
    const float Dt=1f/240f;
    static int Steps=2400;
    static readonly Vector3 VisualOffset=new(0,.617f,.35f);
    static readonly string Output=Environment.GetEnvironmentVariable("HYBRID_CELL_OUTPUT");
    static readonly List<ContactEvent> Contacts=new();
    static readonly List<ColliderBinding> HandColliders=new();
    static Rigidbody target,blueCup,rightBody,leftBody;
    static Transform right,left;
    static readonly List<Digit> rightDigits=new(),leftDigits=new();
    static Vector3 initialTarget;
    static Quaternion turnReference;
    static float maxHeight,minPenetration=0,maxPalmSpeed,maxPalmAngularSpeed,maxClosureRate,rotationDeg;
    static int contactRecoverySteps;
    static float priorCommandedPalmAngle;
    static bool haveCommandedPalmAngle;
    static bool released;
    static bool fullEpisode,reconstructionEpisode;static Vector3 blueInitial;
    static float targetLateral,targetMass=.035f,targetFriction=1f;

    [MenuItem("BabyWorld/Run Hybrid Bimanual Hard Cell")]
    public static void Run()
    {
        if(string.IsNullOrWhiteSpace(Output))throw new Exception("HYBRID_CELL_OUTPUT is required");
        fullEpisode=Environment.GetEnvironmentVariable("HYBRID_FULL_EPISODE")=="1";reconstructionEpisode=Environment.GetEnvironmentVariable("HYBRID_STAGE_C_RECONSTRUCTION")=="1";targetLateral=EnvFloat("HYBRID_TARGET_LATERAL_M",0);targetMass=EnvFloat("HYBRID_TARGET_MASS_KG",.035f);targetFriction=EnvFloat("HYBRID_TARGET_FRICTION",1);Steps=fullEpisode?56*240:reconstructionEpisode?8*240:2400;Directory.CreateDirectory(Output);Directory.CreateDirectory(Path.Combine(Output,"frames"));
        Build();var camera=BuildCamera();var rows=new List<TraceRow>();
        Vector3 priorRight=right.position,priorLeft=left.position;
        var priorSegmentPositions=HandColliders.ToDictionary(x=>x.collider.transform,x=>x.collider.transform.position);var priorSegmentRotations=HandColliders.ToDictionary(x=>x.collider.transform,x=>x.collider.transform.rotation);
        for(int step=0;step<=Steps;step++){
            float t=step*Dt;string phase=fullEpisode?DriveFull(t):reconstructionEpisode?DriveReconstruction(t):Drive(t);
            Physics.SyncTransforms();Physics.Simulate(Dt);Physics.SyncTransforms();MeasureContacts(step);
            float rs=Vector3.Distance(right.position,priorRight)/Dt,ls=Vector3.Distance(left.position,priorLeft)/Dt;
            maxPalmSpeed=Mathf.Max(maxPalmSpeed,rs,ls);
            priorRight=right.position;priorLeft=left.position;
            maxHeight=Mathf.Max(maxHeight,target.position.y-initialTarget.y);float turnStart=fullEpisode?6+5.2f*3.3f:reconstructionEpisode?4.4f:5.2f,turnEnd=fullEpisode?6+6.5f*3.3f:reconstructionEpisode?5.4f:6.5f;if(t>=turnStart&&t<turnStart+Dt*1.1f)turnReference=target.rotation;if(t>=turnStart&&t<=turnEnd)rotationDeg=Mathf.Max(rotationDeg,Quaternion.Angle(turnReference,target.rotation));
            if(step%8==0){Embodiment(t,out Quaternion torso,out Quaternion neck,out Quaternion head);rows.Add(new TraceRow{time_s=t,phase=phase,object_position_m=target.position+VisualOffset,object_rotation=target.rotation,object_velocity_m_s=target.linearVelocity,object_angular_velocity_rad_s=target.angularVelocity,blue_object_position_m=blueCup?blueCup.position+VisualOffset:Vector3.zero,blue_object_rotation=blueCup?blueCup.rotation:Quaternion.identity,blue_object_velocity_m_s=blueCup?blueCup.linearVelocity:Vector3.zero,blue_object_angular_velocity_rad_s=blueCup?blueCup.angularVelocity:Vector3.zero,
                right_palm_position_m=right.position+VisualOffset,left_palm_position_m=left.position+VisualOffset,right_palm_rotation=right.rotation,left_palm_rotation=left.rotation,right_closure=Closure(rightDigits),left_closure=Closure(leftDigits),right_digit_closures=rightDigits.Select(x=>x.value).ToArray(),left_digit_closures=leftDigits.Select(x=>x.value).ToArray(),
                right_digit_segments=SegmentSamples("right",rightDigits,priorSegmentPositions,priorSegmentRotations),left_digit_segments=SegmentSamples("left",leftDigits,priorSegmentPositions,priorSegmentRotations),contacts=FrameContacts(step),avatar_root_position_m=Vector3.zero,avatar_root_rotation=Quaternion.identity,torso_local_delta=torso,neck_local_delta=neck,head_local_delta=head,
                right_contact_recovery=rightDigits.Any(x=>x.recovering),left_contact_recovery=leftDigits.Any(x=>x.recovering),measured_contact_count=Contacts.Count(x=>x.step>=step-7),object_sleeping=target.IsSleeping()});if(!fullEpisode&&!reconstructionEpisode)Capture(camera,Path.Combine(Output,"frames",$"frame_{step/8:D4}.png"));}
        }
        float settleSpeed=target.linearVelocity.magnitude;bool rightContact=Contacts.Any(x=>x.hand=="right"),leftContact=Contacts.Any(x=>x.hand=="left");int rightThumbSteps=Contacts.Where(x=>x.hand=="right"&&x.digit=="thumb").Select(x=>x.step).Distinct().Count();int rightNonThumbSteps=new[]{"index","middle","ring","little"}.Max(name=>Contacts.Where(x=>x.hand=="right"&&x.digit==name).Select(x=>x.step).Distinct().Count());int leftSupportSteps=Contacts.Where(x=>x.hand=="left").Select(x=>x.step).Distinct().Count();int finalContactSteps=Contacts.Where(x=>x.step>Steps-60).Select(x=>x.step).Distinct().Count();int requiredOppositionFrames=0,qualifiedOppositionFrames=0;if(reconstructionEpisode){for(int frame=71;frame<=161;frame++){requiredOppositionFrames++;int end=frame*8;bool thumb=Contacts.Any(x=>x.step>=end-7&&x.step<=end&&x.hand=="right"&&x.digit=="thumb");bool opposed=Contacts.Any(x=>x.step>=end-7&&x.step<=end&&x.hand=="right"&&x.digit!="thumb"&&x.digit!="palm");if(thumb&&opposed)qualifiedOppositionFrames++;}}
        var report=new Report{schema="embodied.hybrid_bimanual_hard_cell.v2",unity_version=Application.unityVersion,physics_hz=240,render_hz=30,steps_per_frame=8,
            controller="kinematic palms and contact-aware kinematic digits; free non-kinematic PhysX object",object_pose_writes_after_initialization=0,object_external_forces=0,
            attachment_or_joint_count=0,assistance_ledger_entries=0,right_measured_contact=rightContact,left_measured_contact=leftContact,
            lift_m=maxHeight,turn_deg=rotationDeg,release_commanded=released,final_object_speed_m_s=settleSpeed,max_finger_penetration_m=-minPenetration,
            max_palm_speed_m_s=maxPalmSpeed,max_palm_angular_speed_deg_s=maxPalmAngularSpeed,max_closure_rate_s=maxClosureRate,available_impulse_status="UNAVAILABLE",duration_s=Steps*Dt,blue_cup_displacement_m=blueCup?Vector3.Distance(blueInitial,blueCup.position):0,target_lateral_m=targetLateral,target_mass_kg=targetMass,target_friction=targetFriction,palm_rotations_recorded=true,per_digit_segment_pose_velocity_recorded=true,object_angular_velocity_recorded=true,head_parent_commands_recorded=true,physics_to_visual_translation_m=VisualOffset,right_thumb_contact_unique_steps=rightThumbSteps,right_non_thumb_contact_unique_steps=rightNonThumbSteps,left_support_contact_unique_steps=leftSupportSteps,final_quarter_second_contact_unique_steps=finalContactSteps,contact_recovery_steps=contactRecoverySteps,required_opposition_render_frames=requiredOppositionFrames,qualified_opposition_render_frames=qualifiedOppositionFrames,continuous_opposition_pass=!reconstructionEpisode||qualifiedOppositionFrames==requiredOppositionFrames};
        report.passed=rightContact&&leftContact&&rightThumbSteps>=60&&rightNonThumbSteps>=60&&leftSupportSteps>=60&&finalContactSteps==0&&report.continuous_opposition_pass&&maxHeight>=.08f&&rotationDeg>=20&&released&&settleSpeed<.08f&&-minPenetration<=.003f&&maxPalmSpeed<=.18f&&maxPalmAngularSpeed<=45&&maxClosureRate<=3.1f&&report.assistance_ledger_entries==0&&(!fullEpisode||report.blue_cup_displacement_m>=.01f);
        File.WriteAllText(Path.Combine(Output,"trace.json"),JsonUtility.ToJson(new Trace{schema="embodied.hybrid_bimanual_trace.v2",coordinate_frame="Unity world metres; raw PhysX positions translated by physics_to_visual_translation_m",physics_to_visual_translation_m=VisualOffset,camera_parent_state="avatar root plus recorded torso/neck/head local deltas; fixed optical mount resolved by the registered skin renderer",rows=rows.ToArray()},true));
        File.WriteAllText(Path.Combine(Output,"contacts.json"),JsonUtility.ToJson(new ContactTrace{rows=Contacts.ToArray()},true));
        File.WriteAllText(Path.Combine(Output,"report.json"),JsonUtility.ToJson(report,true));EditorApplication.Exit(report.passed?0:2);
    }

    static void Build(){Physics.simulationMode=SimulationMode.Script;Physics.gravity=new Vector3(0,-9.81f,0);Physics.defaultSolverIterations=24;Physics.defaultSolverVelocityIterations=12;
        var support=Cube("support",new Vector3(0,.0125f,0),new Vector3(.42f,.025f,.35f),new Color(.62f,.43f,.24f));
        target=Cube("free_red_toy",new Vector3(targetLateral,.053f,0),Vector3.one*.055f,new Color(.85f,.035f,.025f)).AddComponent<Rigidbody>();target.mass=targetMass;target.interpolation=RigidbodyInterpolation.None;target.collisionDetectionMode=CollisionDetectionMode.ContinuousDynamic;target.maxDepenetrationVelocity=.25f;
        var pm=new PhysicsMaterial("target_friction"){staticFriction=targetFriction,dynamicFriction=targetFriction*.9f,frictionCombine=PhysicsMaterialCombine.Maximum,bounciness=0};target.GetComponent<Collider>().material=pm;initialTarget=target.position;
        right=Hand("right",reconstructionEpisode?new Vector3(0,.066f,-.16f):new Vector3(0,.066f,-.20f),new Color(.78f,.49f,.34f),out rightBody,rightDigits);
        left=Hand("left",reconstructionEpisode?new Vector3(-.16f,.15f,.01f):new Vector3(-.18f,.15f,.01f),new Color(.72f,.43f,.30f),out leftBody,leftDigits);
        if(fullEpisode){blueCup=Cube("free_blue_cup",new Vector3(.14f,.063f,-.05f),new Vector3(.06f,.075f,.06f),new Color(.04f,.18f,.85f)).AddComponent<Rigidbody>();blueCup.mass=.05f;blueCup.collisionDetectionMode=CollisionDetectionMode.ContinuousDynamic;blueCup.GetComponent<Collider>().material=pm;blueInitial=blueCup.position;}
        var light=new GameObject("key_light").AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.5f;light.transform.rotation=Quaternion.Euler(48,-28,0);RenderSettings.ambientLight=new Color(.32f,.30f,.28f);Physics.SyncTransforms();}
    static Transform Hand(string side,Vector3 position,Color color,out Rigidbody rb,List<Digit> digits){var root=new GameObject(side+"_hand_root").transform;root.position=position;rb=root.gameObject.AddComponent<Rigidbody>();rb.isKinematic=true;rb.collisionDetectionMode=CollisionDetectionMode.ContinuousSpeculative;var palm=Cube(side+"_palm",Vector3.zero,new Vector3(.07f,.075f,.018f),color);palm.transform.SetParent(root,false);HandColliders.Add(new ColliderBinding{collider=palm.GetComponent<Collider>(),hand=side,digit="palm"});
        string[] names={"thumb","index","middle","ring","little"};float[] ys={-.005f,.029f,.014f,-.003f,-.021f};float[] xs={-.046f,.046f,.048f,.048f,.045f};
        for(int d=0;d<5;d++){float closedMagnitude=d==0?.0325f:.034f;var digit=new Digit{name=names[d],side=side,openX=xs[d],closedX=Mathf.Sign(xs[d])*closedMagnitude};for(int p=0;p<3;p++){var seg=Cube(side+"_"+names[d]+"_"+(p+1),Vector3.zero,new Vector3(.015f,.015f,.030f),color);seg.transform.SetParent(root,false);seg.transform.localPosition=new Vector3(xs[d],ys[d],.018f+p*.027f);HandColliders.Add(new ColliderBinding{collider=seg.GetComponent<Collider>(),hand=side,digit=names[d]});digit.segments.Add(seg.transform);}digits.Add(digit);}return root;}
    static string Drive(float t){Vector3 r0=new(0,.066f,-.20f),rContact=new(0,.066f,-.0345f),rLift=new(0,.166f,-.0345f),rPlace=new(-.09f,.070f,.08f);Vector3 l0=new(-.18f,.15f,.01f),lAssist=new(-.075f,.166f,-.005f);Vector3 leftPlace=rPlace+new Vector3(-.084f,0,.03f);
        string phase;Vector3 rp,lp;Quaternion rr=Quaternion.identity,lr=Quaternion.identity;float rc=0,lc=0,commandedPalmAngle=0;
        if(t<1.5f){phase="right_reach";rp=Vector3.Lerp(r0,rContact,Smooth(t/1.5f));lp=l0;}
        else if(t<2.4f){phase="contact_aware_capture";rp=rContact;lp=l0;rc=Smooth((t-1.5f)/.9f);}
        else if(t<4.0f){phase="lift";rp=Vector3.Lerp(rContact,rLift,Smooth((t-2.4f)/1.6f));lp=l0;rc=1;}
        else if(t<5.2f){phase="left_assist";rp=rLift;lp=Vector3.Lerp(l0,lAssist,Smooth((t-4)/1.2f));rc=1;lc=Smooth((t-4.7f)/.5f);}
        else if(t<6.5f){phase="bimanual_turn";float a=25*Smooth((t-5.2f)/1.3f);commandedPalmAngle=a;rr=Quaternion.Euler(0,0,a);lr=rr;rp=rLift;lp=lAssist;rc=lc=1;}
        else if(t<8.0f){phase="lower_place";float u=Smooth((t-6.5f)/1.5f);commandedPalmAngle=25*(1-u);rr=Quaternion.Euler(0,0,commandedPalmAngle);lr=rr;rp=Vector3.Lerp(rLift,rPlace,u);lp=Vector3.Lerp(lAssist,leftPlace,u);rc=1;lc=1-u;}
        else if(t<8.7f){phase="commanded_open_release";rp=rPlace;lp=leftPlace;rc=1-Smooth((t-8)/.7f);released=true;}
        else{phase=t<9.4f?"free_settle":"withdrawal";float u=Smooth((t-8.7f)/1.3f);rp=Vector3.Lerp(rPlace,new Vector3(-.09f,.11f,-.04f),u);lp=Vector3.Lerp(leftPlace,new Vector3(-.20f,.13f,.00f),u);}
        TrackPalmAngle(commandedPalmAngle);Move(rightBody,rp,rr);Move(leftBody,lp,lr);SetClosure(rightDigits,rc);SetClosure(leftDigits,lc);return phase;}
    static string DriveReconstruction(float t){Vector3 r0=new(0,.066f,-.16f),rContact=new(0,.066f,-.040f),rLift=new(0,.156f,-.040f),rPlace=new(-.033f,.089f,-.043f);Vector3 l0=new(-.16f,.15f,.01f),lAssist=new(-.0675f,.156f,-.005f);Vector3 leftPlace=new(-.149f,.070f,.020f);
        string phase;Vector3 rp,lp;Quaternion rr=Quaternion.identity,lr=Quaternion.identity;float rc=0,lc=0,commandedPalmAngle=0;
        if(t<.4f){phase="stabilize_and_orient";rp=r0;lp=l0;}
        else if(t<1.5f){phase="contact_free_reach";rp=Vector3.Lerp(r0,rContact,Smooth((t-.4f)/1.1f));lp=l0;}
        else if(t<2.3f){phase="visible_touch_and_capture";rp=rContact;lp=l0;rc=Smooth((t-1.5f)/.8f);}
        else if(t<3.3f){phase="physical_lift";rp=Vector3.Lerp(rContact,rLift,Smooth((t-2.3f)));lp=l0;rc=1;}
        else if(t<4.4f){phase="left_hand_support";rp=rLift;lp=Vector3.Lerp(l0,lAssist,Smooth((t-3.3f)/1.1f));rc=1;lc=Smooth((t-3.80f)/.55f);}
        else if(t<5.4f){phase="bimanual_inspect_turn";float a=25*Smooth(t-4.4f);commandedPalmAngle=a;Quaternion orbit=Quaternion.Euler(0,0,a);Vector3 pivot=new(initialTarget.x,initialTarget.y+.09f,initialTarget.z);rr=lr=orbit;rp=pivot+orbit*(rLift-pivot);lp=pivot+orbit*(lAssist-pivot);rc=lc=1;}
        else if(t<6.6f){phase="lower_to_support";float u=Smooth((t-5.4f)/1.2f);Quaternion endOrbit=Quaternion.Euler(0,0,25);Vector3 pivot=new(initialTarget.x,initialTarget.y+.09f,initialTarget.z);Vector3 rTurn=pivot+endOrbit*(rLift-pivot),lTurn=pivot+endOrbit*(lAssist-pivot);commandedPalmAngle=25*(1-u);rr=Quaternion.Euler(0,0,commandedPalmAngle);lr=rr;rp=Vector3.Lerp(rTurn,rPlace,u);lp=Vector3.Lerp(lTurn,leftPlace,u);rc=1;lc=1-u;}
        else if(t<7.15f){phase="commanded_open_free_release";rp=rPlace;lp=leftPlace;rc=1-Smooth((t-6.6f)/.55f);released=true;}
        else{phase=t<7.45f?"free_settle":"hand_withdrawal";float u=Smooth((t-7.15f)/.85f);rp=Vector3.Lerp(rPlace,new Vector3(-.033f,.120f,-.135f),u);lp=Vector3.Lerp(leftPlace,new Vector3(-.185f,.115f,-.060f),u);}
        TrackPalmAngle(commandedPalmAngle);Move(rightBody,rp,rr);Move(leftBody,lp,lr);SetClosure(rightDigits,rc);SetClosure(leftDigits,lc);return phase;}
    static string DriveFull(float t){if(t<6){TrackPalmAngle(0);Move(rightBody,new Vector3(0,.066f,-.20f),Quaternion.identity);Move(leftBody,new Vector3(-.18f,.15f,.01f),Quaternion.identity);SetClosure(rightDigits,0);SetClosure(leftDigits,0);return t<3?"scan_reorient":"gaze_red_toy";}if(t<39)return Drive((t-6)/3.3f);Vector3 leftEnd=new(-.20f,.13f,0),leftRest=new(-.18f,.14f,-.12f);Move(leftBody,t<41?Vector3.Lerp(leftEnd,leftRest,Smooth((t-39)/2)):leftRest,Quaternion.identity);SetClosure(leftDigits,0);Vector3 a=new(-.09f,.11f,-.25f),b=new(.14f,.11f,-.25f),c=new(.14f,.075f,-.085f),d=new(.14f,.075f,-.065f),e=new(.06f,.14f,-.20f);Vector3 rp;string phase;if(t<41){phase="withdraw_from_red";rp=Vector3.Lerp(new Vector3(-.09f,.11f,-.04f),a,Smooth((t-39)/2));}else if(t<43){phase="gaze_blue_cup_reach";rp=Vector3.Lerp(a,b,Smooth((t-41)/2));}else if(t<45){phase="blue_cup_touch";rp=Vector3.Lerp(b,c,Smooth((t-43)/2));}else if(t<46){phase="blue_cup_touch_push";rp=Vector3.Lerp(c,d,Smooth(t-45));}else if(t<48){phase="blue_cup_withdraw";rp=Vector3.Lerp(d,e,Smooth((t-46)/2));}else{phase=t<52?"final_withdrawal":"look_window_settle";rp=e;}TrackPalmAngle(0);Move(rightBody,rp,Quaternion.identity);SetClosure(rightDigits,0);return phase;}
    static void Embodiment(float t,out Quaternion torso,out Quaternion neck,out Quaternion head){float down=.78f+.22f*Smooth(t/.75f);float scan=(1-Smooth(t/.8f))*-10f;float inspect=(Smooth((t-4.25f)/.7f)-Smooth((t-5.45f)/.65f))*5f;float releaseUp=Smooth((t-7.35f)/.65f);torso=Quaternion.Euler(10f*down*(1-.20f*releaseUp),0,0);neck=Quaternion.Euler(14f*down*(1-.15f*releaseUp),0,0);head=Quaternion.Euler(42f*down*(1-.10f*releaseUp),scan+inspect,-1.0f*inspect/5f);}
    static SegmentSample[] SegmentSamples(string side,List<Digit> digits,Dictionary<Transform,Vector3> priorPositions,Dictionary<Transform,Quaternion> priorRotations){var result=new List<SegmentSample>();foreach(var d in digits)for(int i=0;i<d.segments.Count;i++){var s=d.segments[i];Vector3 p=s.position;Quaternion q=s.rotation;Vector3 velocity=(p-priorPositions[s])/(8*Dt);Quaternion delta=q*Quaternion.Inverse(priorRotations[s]);delta.ToAngleAxis(out float angle,out Vector3 axis);if(angle>180)angle-=360;Vector3 angular=axis.sqrMagnitude>0?axis.normalized*(angle*Mathf.Deg2Rad/(8*Dt)):Vector3.zero;result.Add(new SegmentSample{name=$"{side}_{d.name}_{i+1}",digit=d.name,segment=i+1,position_m=p+VisualOffset,rotation=q,linear_velocity_m_s=velocity,angular_velocity_rad_s=angular});priorPositions[s]=p;priorRotations[s]=q;}return result.ToArray();}
    static ContactSample[] FrameContacts(int step)=>Contacts.Where(x=>x.step>=step-7).GroupBy(x=>$"{x.hand}:{x.digit}").Select(g=>g.OrderBy(x=>Vector3.Distance(x.point_m,x.hand=="right"?right.position:left.position)).First()).Select(x=>new ContactSample{hand=x.hand,digit=x.digit,point_m=x.point_m+VisualOffset,normal=x.normal,separation_m=x.separation_m}).ToArray();
    static void TrackPalmAngle(float angle){if(haveCommandedPalmAngle)maxPalmAngularSpeed=Mathf.Max(maxPalmAngularSpeed,Mathf.Abs(Mathf.DeltaAngle(priorCommandedPalmAngle,angle))/Dt);priorCommandedPalmAngle=angle;haveCommandedPalmAngle=true;}
    static void Move(Rigidbody rb,Vector3 p,Quaternion q){rb.MovePosition(p);rb.MoveRotation(q);}
    static void SetClosure(List<Digit> digits,float value){value=Mathf.Clamp01(value);foreach(var d in digits){float prior=d.value;d.recovering=false;if(d.side=="right"&&d.penetration_m>.00235f&&value>=prior){d.value=Mathf.MoveTowards(prior,0,3f*Dt);d.recovering=true;contactRecoverySteps++;}else if(value<prior){d.value=Mathf.MoveTowards(prior,value,3f*Dt);d.touchingTarget=false;}else if(!d.touchingTarget)d.value=Mathf.MoveTowards(prior,value,3f*Dt);maxClosureRate=Mathf.Max(maxClosureRate,Mathf.Abs(d.value-prior)/Dt);float x=Mathf.Lerp(d.openX,d.closedX,d.value);foreach(var s in d.segments){var p=s.localPosition;p.x=x;s.localPosition=p;}}}
    static float Closure(List<Digit> digits)=>digits.Average(x=>x.value);
    static void MeasureContacts(int step){foreach(var d in rightDigits.Concat(leftDigits)){d.touchingTarget=false;d.penetration_m=0;}var objectCollider=target.GetComponent<Collider>();foreach(var b in HandColliders){if(Physics.ComputePenetration(b.collider,b.collider.transform.position,b.collider.transform.rotation,objectCollider,objectCollider.transform.position,objectCollider.transform.rotation,out Vector3 direction,out float distance)){minPenetration=Mathf.Min(minPenetration,-distance);var list=b.hand=="right"?rightDigits:leftDigits;var d=list.FirstOrDefault(x=>x.name==b.digit);if(d!=null){d.touchingTarget=true;d.penetration_m=Mathf.Max(d.penetration_m,distance);}Contacts.Add(new ContactEvent{step=step,time_s=step*Dt,hand=b.hand,digit=b.digit,point_m=TargetSurfacePoint(b.collider.bounds.center),normal=direction,separation_m=-distance});}}}
    static Vector3 TargetSurfacePoint(Vector3 query){var box=(BoxCollider)target.GetComponent<Collider>();Vector3 local=target.transform.InverseTransformPoint(query)-box.center;Vector3 half=box.size*.5f;bool inside=Mathf.Abs(local.x)<=half.x&&Mathf.Abs(local.y)<=half.y&&Mathf.Abs(local.z)<=half.z;local=new Vector3(Mathf.Clamp(local.x,-half.x,half.x),Mathf.Clamp(local.y,-half.y,half.y),Mathf.Clamp(local.z,-half.z,half.z));if(inside){float dx=half.x-Mathf.Abs(local.x),dy=half.y-Mathf.Abs(local.y),dz=half.z-Mathf.Abs(local.z);if(dx<=dy&&dx<=dz)local.x=Mathf.Sign(local.x==0?1:local.x)*half.x;else if(dy<=dz)local.y=Mathf.Sign(local.y==0?1:local.y)*half.y;else local.z=Mathf.Sign(local.z==0?1:local.z)*half.z;}return target.transform.TransformPoint(local+box.center);}
    static Camera BuildCamera(){var c=new GameObject("qa_camera").AddComponent<Camera>();c.transform.position=new Vector3(.58f,.42f,-.58f);c.transform.LookAt(new Vector3(0,.09f,.02f));c.fieldOfView=42;c.nearClipPlane=.02f;c.backgroundColor=new Color(.12f,.15f,.18f);return c;}
    static GameObject Cube(string name,Vector3 position,Vector3 scale,Color color){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.name=name;go.transform.position=position;go.transform.localScale=scale;var mat=new Material(Shader.Find("Standard"));mat.color=color;go.GetComponent<Renderer>().sharedMaterial=mat;return go;}
    static void Capture(Camera c,string path){var rt=new RenderTexture(960,540,24);var tex=new Texture2D(960,540,TextureFormat.RGB24,false);c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,960,540),0,0);tex.Apply();File.WriteAllBytes(path,tex.EncodeToPNG());c.targetTexture=null;RenderTexture.active=null;UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(tex);}
    static float Smooth(float x){x=Mathf.Clamp01(x);return x*x*(3-2*x);}
    static float EnvFloat(string name,float fallback){return float.TryParse(Environment.GetEnvironmentVariable(name),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out float value)?value:fallback;}
    class Digit{public string name,side;public float openX,closedX,value,penetration_m;public bool touchingTarget,recovering;public readonly List<Transform> segments=new();}class ColliderBinding{public Collider collider;public string hand,digit;}
    [Serializable]class Trace{public string schema,coordinate_frame,camera_parent_state;public Vector3 physics_to_visual_translation_m;public TraceRow[] rows;}[Serializable]class ContactTrace{public ContactEvent[] rows;}
    [Serializable]class TraceRow{public float time_s;public string phase;public Vector3 object_position_m,blue_object_position_m;public Quaternion object_rotation,blue_object_rotation;public Vector3 object_velocity_m_s,blue_object_velocity_m_s,object_angular_velocity_rad_s,blue_object_angular_velocity_rad_s,right_palm_position_m,left_palm_position_m;public Quaternion right_palm_rotation,left_palm_rotation;public float right_closure,left_closure;public float[] right_digit_closures,left_digit_closures;public SegmentSample[] right_digit_segments,left_digit_segments;public ContactSample[] contacts;public Vector3 avatar_root_position_m;public Quaternion avatar_root_rotation,torso_local_delta,neck_local_delta,head_local_delta;public int measured_contact_count;public bool right_contact_recovery,left_contact_recovery,object_sleeping;}
    [Serializable]class SegmentSample{public string name,digit;public int segment;public Vector3 position_m,linear_velocity_m_s,angular_velocity_rad_s;public Quaternion rotation;}
    [Serializable]class ContactSample{public string hand,digit;public Vector3 point_m,normal;public float separation_m;}
    [Serializable]public class ContactEvent{public int step;public float time_s;public string hand,digit;public Vector3 point_m,normal;public float separation_m;}
    [Serializable]class Report{public string schema,unity_version,controller,available_impulse_status;public int physics_hz,render_hz,steps_per_frame,object_pose_writes_after_initialization,object_external_forces,attachment_or_joint_count,assistance_ledger_entries,right_thumb_contact_unique_steps,right_non_thumb_contact_unique_steps,left_support_contact_unique_steps,final_quarter_second_contact_unique_steps,contact_recovery_steps,required_opposition_render_frames,qualified_opposition_render_frames;public bool right_measured_contact,left_measured_contact,release_commanded,palm_rotations_recorded,per_digit_segment_pose_velocity_recorded,object_angular_velocity_recorded,head_parent_commands_recorded,continuous_opposition_pass,passed;public Vector3 physics_to_visual_translation_m;public float duration_s,target_lateral_m,target_mass_kg,target_friction,lift_m,turn_deg,blue_cup_displacement_m,final_object_speed_m_s,max_finger_penetration_m,max_palm_speed_m_s,max_palm_angular_speed_deg_s,max_closure_rate_s;}
}
